steps:
  - name: "gcr.io/cloud-builders/wget"
    args:
      [
        "https://releases.hashicorp.com/packer/1.11.1/packer_1.11.1_linux_amd64.zip",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/orbital-bee-455915-h5/packer/packer",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/orbital-bee-455915-h5/packer/packer",
      ]
tags: ["cloud-builders-community"]

options:
  logging: CLOUD_LOGGING_ONLY
