steps:
  - name: "gcr.io/cloud-builders/wget"
    args:
      [
        "https://releases.hashicorp.com/packer/1.11.1/packer_1.11.1_linux_amd64.zip",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "packer", "."]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "https://us-central1-docker.pkg.dev/custom-ground-424107-q4/packer:latest",
      ]
images:
  - "https://us-central1-docker.pkg.dev/custom-ground-424107-q4/packer:latest"
tags: ["cloud-builders-community"]

options:
  logging: CLOUD_LOGGING_ONLY
