steps:
  - name: "us-central1-docker.pkg.dev/orbital-bee-455915-h5/packer/packer"
    args:
      - init
      - -var-file=variables.pkrvars.hcl
      - ubuntu.pkr.hcl
  - name: "us-central1-docker.pkg.dev/orbital-bee-455915-h5/packer/packer"
    args:
      - build
      - -var-file=variables.pkrvars.hcl
      - ubuntu.pkr.hcl
tags: ["cloud-builders-community"]
options:
  logging: CLOUD_LOGGING_ONLY
